SET DATABASE UNIQUE NAME HSQLDB7CCBC8BCCE
SET DATABASE GC 0
SET DATABASE DEFAULT RESULT MEMORY ROWS 0
SET DATABASE EVENT LOG LEVEL 0
SET DATABASE TRANSACTION CONTROL LOCKS
SET DATABASE DEFAULT ISOLATION LEVEL READ COMMITTED
SET DATABASE TRANSACTION ROLLBACK ON CONFLICT TRUE
SET DATABASE TEXT TABLE DEFAULTS ''
SET DATABASE SQL NAMES FALSE
SET DATABASE SQL REFERENCES FALSE
SET DATABASE SQL SIZE TRUE
SET DATABASE SQL TYPES FALSE
SET DATABASE SQL TDC DELETE TRUE
SET DATABASE SQL TDC UPDATE TRUE
SET DATABASE SQL CONCAT NULLS TRUE
SET DATABASE SQL UNIQUE NULLS TRUE
SET DATABASE SQL CONVERT TRUNCATE TRUE
SET DATABASE SQL AVG SCALE 0
SET DATABASE SQL DOUBLE NAN TRUE
SET FILES WRITE DELAY 500 MILLIS
SET FILES BACKUP INCREMENT TRUE
SET FILES CACHE SIZE 10000
SET FILES CACHE ROWS 50000
SET FILES SCALE 32
SET FILES LOB SCALE 32
SET FILES DEFRAG 0
SET FILES NIO TRUE
SET FILES NIO SIZE 256
SET FILES LOG TRUE
SET FILES LOG SIZE 50
SET FILES CHECK 8289
SET DATABASE COLLATION "SQL_TEXT" PAD SPACE
CREATE USER SA PASSWORD DIGEST 'd41d8cd98f00b204e9800998ecf8427e'
ALTER USER SA SET LOCAL TRUE
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE MEMORY TABLE PUBLIC.BANK(ID BINARY(255) NOT NULL PRIMARY KEY)
CREATE MEMORY TABLE PUBLIC.CREDIT(ID BINARY(255) NOT NULL PRIMARY KEY,CREDIT_LIMIT BIGINT,CREDIT_PERCENT DOUBLE NOT NULL,CHECK((PUBLIC.CREDIT.CREDIT_LIMIT<=99999999) AND (PUBLIC.CREDIT.CREDIT_LIMIT>=1000)))
CREATE MEMORY TABLE PUBLIC.CUSTOMER(ID BINARY(255) NOT NULL PRIMARY KEY,EMAIL VARCHAR(255),NAME VARCHAR(255),PASSPORT VARCHAR(255),PHONE VARCHAR(255))
CREATE MEMORY TABLE PUBLIC.OFFER(ID BINARY(255) NOT NULL PRIMARY KEY,CREDIT_SUM BIGINT,CREDIT_ID BINARY(255),CUSTOMER_ID BINARY(255),CHECK((PUBLIC.OFFER.CREDIT_SUM<=99999999) AND (PUBLIC.OFFER.CREDIT_SUM>=1000)),CONSTRAINT FKLRBDWF6ATJX5KF10H12IGMXRJ FOREIGN KEY(CREDIT_ID) REFERENCES PUBLIC.CREDIT(ID),CONSTRAINT FK15VU7345G8UAP5VAGD9SDC9DO FOREIGN KEY(CUSTOMER_ID) REFERENCES PUBLIC.CUSTOMER(ID))
CREATE MEMORY TABLE PUBLIC.REPAYMENT(ID BINARY(255) NOT NULL PRIMARY KEY,DATE DATE,LOAN_REPAYMENT BIGINT,MONTH_PAY BIGINT,PERCENT_REPAYMENT BIGINT,OFFER_ID BINARY(255),CONSTRAINT FKNVIJWKKCLLHQU80BBF6YXMO86 FOREIGN KEY(OFFER_ID) REFERENCES PUBLIC.OFFER(ID))
ALTER SEQUENCE SYSTEM_LOBS.LOB_ID RESTART WITH 1
SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CARDINAL_NUMBER TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.YES_OR_NO TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CHARACTER_DATA TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.SQL_IDENTIFIER TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.TIME_STAMP TO PUBLIC
GRANT DBA TO SA
SET SCHEMA SYSTEM_LOBS
INSERT INTO BLOCKS VALUES(0,2147483647,0)
